# Generated by Django 4.2.11 on 2024-03-16 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organic_eire', '0004_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_on']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on']},
        ),
    ]
