# Generated by Django 4.2.11 on 2024-03-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_links_description_links_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='links',
            name='updated_on',
        ),
    ]
