# Generated by Django 4.2.11 on 2024-03-24 11:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0003_remove_links_updated_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='link_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
